services:
  spark-master:
    image: bitnami/spark
    networks:
      - spark_network

  spark-driver:
    image: bitnami/spark
    container_name: spark-connect
    environment:
      - SPARK_MODE=driver
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - spark_network
    depends_on:
      - spark-master
    command: ["/bin/bash", "-c", "/opt/bitnami/spark/sbin/start-connect-server.sh --master spark://spark-master:7077 --packages org.apache.spark:spark-connect_2.12:3.5.1"]

  spark-worker-1:
    image: bitnami/spark
    networks:
      - spark_network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077

  spark-worker-2:
    image: bitnami/spark
    networks:
      - spark_network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077

  spark-worker-3:
    image: bitnami/spark
    networks:
      - spark_network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077

networks:
  spark_network:
