x-spark: &x-spark
  image: bitnami/spark:3.5.1
  networks:
    - spark_network

x-worker: &x-worker
  <<: *x-spark
  environment:
    SPARK_MODE: worker
    SPARK_MASTER: spark://spark-master:7077
  depends_on:
    - spark-master

services:
  spark-master:
    <<: *x-spark

  spark-driver:
    <<: *x-spark
    command: ["/bin/bash", "-c", "/opt/bitnami/spark/sbin/start-connect-server.sh --master spark://spark-master:7077 --packages org.apache.spark:spark-connect_2.12:3.5.1"]
    depends_on:
      - spark-master

  spark-worker-1:
    <<: *x-worker

  spark-worker-2:
    <<: *x-worker

  spark-worker-3:
    <<: *x-worker

networks:
  spark_network:
    name: spark_network
