x-spark: &x-spark
  image: bitnami/spark
  networks:
    - spark_network

x-spark-master-uri: &x-spark-master-uri
  SPARK_MASTER: spark://spark-master:7077

x-worker: &x-worker
  <<: *x-spark
  environment:
    SPARK_MODE: worker
    <<: *x-spark-master-uri
  depends_on:
    - spark-master

services:
  spark-master:
    <<: *x-spark

  spark-driver:
    <<: *x-spark
    environment:
      SPARK_MODE: driver
      <<: *x-spark-master-uri
    command: ["/bin/bash", "-c", "/opt/bitnami/spark/sbin/start-connect-server.sh --master spark://spark-master:7077 --packages org.apache.spark:spark-connect_2.12:3.5.1"]
    depends_on:
      - spark-master

  spark-worker-1:
    <<: *x-worker

  spark-worker-2:
    <<: *x-worker

  spark-worker-3:
    <<: *x-worker

networks:
  spark_network:
    name: spark_network
